### ISSUE TITLE
Where Does WinServiceMgr store its Configuration File?

### ISSUE THREAD

**Issue by ghost** [simonclausen/dnscrypt-winservicemgr#1]
Hello,

The service on Windows started disconnecting about two weeks ago, I occasionally had to Disable and Re-enable the WIFI adapter several times to get it fixed (also changing DNS server address in there to public DNS, then back to localhost helped).

Today, it went completely bust. I tried the above, then tried "installing" and "uninstalling" it using its cool GUI, but still nothing.

How can I remove it completely from my Windows 8.1 system to prepare it for re-installation?

Thanks.
Sorry to bother with consumer-level questions, without being helpful in code.

**Comment by simonclausen** [comment]
Hi,

No problem. There are no configs stored as. The registry and NIC settings are read and then altered according to user input.

Disabling the service via the GUI _should_ remove everything. You can double check if there is still anything in the following registry path: "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dnscrypt-proxy" to make sure everything is removed.

Have you tried configuring different DNSCrypt servers?

**Comment by ghost** [comment]
@simonclausen I did indeed. I tried several and my browsers say "DNS lookup failed" but it works with public DNS.

If I didn't get this right, I'll probably re-install Windows. It's already past due time anyway for this ***\* OS, lol.

Thank you for your work on this as well as the Linux one. I, and a lot like me, really appreciate it.

**Comment by simonclausen** [comment]
Are you also ticking removing the tickoff by the NIC? If this is still there Windows will try to use DNSCrypt, even though the service is not running (Bad implementation)

**Comment by ghost** [comment]
@simonclausen Awesome, you've just fixed it :)

I pasted "dnscrypt-proxy" in registry search and found several results including things from 1.4 version. I deleted them, then re-enabled DNSCrypt, now it works.

Correction: I see it's at 0.2 version :/

But I saw things that has the label 1.4 and DNSCrypt name. Sorry,
it was just a desperate hit and run move. Didn't record their paths.

**Comment by simonclausen** [comment]
Ok, good. If there's stuff way back from 0.2 that might explain your issues.

So everything is good?

**Comment by ghost** [comment]
HKEY_USERS\S-1-5-21-792283616-1883273252-2852134058-1001\Software\WinRAR\DialogEditHistory\ExtrPath

There were items named "1" and "2" and I deleted them, along with others on a different path. 

Yep, now it's good thanks.

**Comment by simonclausen** [comment]
Good to hear.
